"""
Stimuli management for the Social Influence Task.

Important: this task involves NO chatbot interaction and NO LLM calls.
Participants simply see a pre-set rating number next to each artwork and
re-rate it themselves. The "agent" is just a label (Alex, Sam, Casey, Jordan,
or RNG) paired with a fixed number stored in agent_ratings.json.

What this module does:
  - Loads artworks from stimuli/artworks.json
  - Loads pre-set agent ratings from stimuli/agent_ratings.json
  - Assigns artworks to conditions for each participant (counterbalancing)
  - Builds Phase 1 and Phase 2 trial lists

Artwork–condition assignment:
  5 conditions: Alex, Sam, Casey, Jordan, RNG
  75 artworks:  15 per condition
  Rotation:     every 5 participants = 1 complete rotation
  Rule:         (artwork_id − 1 + participant_index) mod 5 → condition
"""

import json
import random
from pathlib import Path

STIMULI_DIR = Path(__file__).parent / "stimuli"
ARTWORKS_FILE = STIMULI_DIR / "artworks.json"
AGENT_RATINGS_FILE = STIMULI_DIR / "agent_ratings.json"

AGENT_CONDITIONS = ["Alex", "Sam", "Casey", "Jordan", "RNG"]
N_CONDITIONS = len(AGENT_CONDITIONS)        # 5
TRIALS_PER_CONDITION = 15
TOTAL_ARTWORKS = N_CONDITIONS * TRIALS_PER_CONDITION  # 75


def load_artworks() -> list[dict]:
    """Load the full artwork stimulus list from artworks.json."""
    return json.loads(ARTWORKS_FILE.read_text())


def load_agent_ratings() -> dict[str, dict[str, int]]:
    """
    Load pre-set agent ratings from agent_ratings.json.

    Format:
    {
      "Alex":   {"1": 72, "2": 45, ...},
      "Sam":    {"1": 60, "2": 38, ...},
      "Casey":  {"1": 65, "2": 50, ...},
      "Jordan": {"1": 58, "2": 42, ...}
    }

    RNG ratings are generated at runtime (reproducible per artwork_id).
    These numbers are fixed before the study runs and never change.
    They are NOT generated by an LLM — just pre-set numbers chosen to
    span the 0–100 range plausibly.
    """
    if AGENT_RATINGS_FILE.exists():
        return json.loads(AGENT_RATINGS_FILE.read_text())
    # File not yet created — return empty dict, fallback will apply
    return {}


def get_agent_rating(condition: str, artwork_id: int, ratings: dict) -> int:
    """
    Look up the pre-set rating for a given condition and artwork.

    For RNG: uses a fixed random seed per artwork so all participants see
    the same RNG number for any given artwork.

    For named agents (Alex/Sam/Casey/Jordan): reads from agent_ratings.json.
    If the file doesn't exist yet, falls back to a deterministic placeholder —
    replace with real ratings before running participants.
    """
    if condition == "RNG":
        # Fixed seed per artwork → same RNG number for all participants
        rng = random.Random(artwork_id * 1337)
        return rng.randint(10, 90)

    condition_ratings = ratings.get(condition, {})
    rating = condition_ratings.get(str(artwork_id))
    if rating is not None:
        return int(rating)

    # Fallback placeholder — replace agent_ratings.json before running
    rng = random.Random(hash(condition) + artwork_id)
    return rng.randint(30, 80)


def assign_artworks_to_conditions(participant_index: int) -> dict[str, list[dict]]:
    """
    Assign all 75 artworks to the 5 conditions for a given participant.

    Returns: {condition_name: [artwork_dict, ...]}
    Each artwork appears in exactly one condition per participant.
    Across every 5 participants, each artwork appears in each condition once.
    """
    artworks = load_artworks()
    assert len(artworks) == TOTAL_ARTWORKS, (
        f"Expected {TOTAL_ARTWORKS} artworks in artworks.json, got {len(artworks)}. "
        "Add all 75 artworks before running participants."
    )

    offset = participant_index % N_CONDITIONS
    assignment: dict[str, list[dict]] = {c: [] for c in AGENT_CONDITIONS}

    for artwork in artworks:
        condition_idx = ((artwork["id"] - 1) + offset) % N_CONDITIONS
        condition = AGENT_CONDITIONS[condition_idx]
        assignment[condition].append(artwork)

    return assignment


def build_phase1_trials(
    participant_index: int,
    seed: int | None = None,
) -> list[dict]:
    """
    Phase 1 baseline: all 75 artworks shuffled, no agent info.
    Participant rates each on 0–100 slider with no anchor shown.
    """
    artworks = load_artworks()
    trials = [
        {
            "artwork_id": a["id"],
            "title": a["title"],
            "artist": a["artist"],
            "year": a["year"],
            "image_url": a.get("image_url", ""),
            "wikiart_url": a.get("wikiart_url", ""),
            "trial_index": i,
        }
        for i, a in enumerate(artworks)
    ]
    # Shuffle independently from Phase 2 so order is different
    rng = random.Random((seed or participant_index) + 99999)
    rng.shuffle(trials)
    for i, t in enumerate(trials):
        t["trial_index"] = i
    return trials


def build_phase2_trials(
    participant_index: int,
    seed: int | None = None,
) -> list[dict]:
    """
    Phase 2 influence: all 75 artworks interleaved across conditions.

    Each trial shows the artwork + the assigned agent's pre-set rating.
    The participant then re-rates on 0–100.

    No LLM involved. agent_rating is just a number read from agent_ratings.json.
    """
    assignment = assign_artworks_to_conditions(participant_index)
    ratings = load_agent_ratings()

    trials = []
    for condition, artworks in assignment.items():
        for artwork in artworks:
            agent_rating = get_agent_rating(condition, artwork["id"], ratings)
            trials.append({
                "artwork_id": artwork["id"],
                "title": artwork["title"],
                "artist": artwork["artist"],
                "year": artwork["year"],
                "image_url": artwork.get("image_url", ""),
                "wikiart_url": artwork.get("wikiart_url", ""),
                "agent_condition": condition,   # which agent label is shown
                "agent_rating": agent_rating,   # the number shown to participant
            })

    rng = random.Random(seed or participant_index)
    rng.shuffle(trials)
    for i, t in enumerate(trials):
        t["trial_index"] = i

    return trials
